from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser
from .models import UploadedFile
from .serializers import FileUploadSerializer
import pandas as pd
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from rest_framework.generics import ListAPIView
import io
import os

# 1. Upload API
class FileUploadView(APIView):
    parser_classes = (MultiPartParser, FormParser)
    serializer_class = FileUploadSerializer

    def post(self, request, *args, **kwargs):
        serializer = FileUploadSerializer(data=request.data)

        if serializer.is_valid():
            files = UploadedFile.objects.all().order_by('uploaded_at')
            if files.count() >= 5:
                oldest_file = files.first()
                oldest_file.delete()

            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# 2. Statistics API
class FileStatsView(APIView):
    def get(self, request, pk, *args, **kwargs):
        try:
            file_obj = UploadedFile.objects.get(pk=pk)
            
            file_path = file_obj.file.path
            df = pd.read_csv(file_path)

            df.columns = df.columns.str.strip()

            required_cols = ['Equipment Name', 'Type', 'Flowrate', 'Pressure', 'Temperature']

            total_count = len(df)
            avg_temp = df['Temperature'].mean() if 'Temperature' in df else 0
            avg_pressure = df['Pressure'].mean() if 'Pressure' in df else 0
            avg_flowrate = df['Flowrate'].mean() if 'Flowrate' in df else 0

            type_distribution = df['Type'].value_counts().to_dict() if 'Type' in df else {}

            data = {
                "filename": os.path.basename(file_path),
                "total_count": total_count,
                "average_metrics": {
                    "temperature": round(avg_temp, 2),
                    "pressure": round(avg_pressure, 2),
                    "flowrate": round(avg_flowrate, 2),
                },
                "type_distribution": type_distribution
            }

            return Response(data, status=status.HTTP_200_OK)

        except UploadedFile.DoesNotExist:
            return Response({"error": "File not found"}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        
class FileReportView(APIView):
    def get(self, request, pk, *args, **kwargs):
        try:
            file_obj = UploadedFile.objects.get(pk=pk)
            df = pd.read_csv(file_obj.file.path)

            total_count = len(df)
            avg_temp = df['Temperature'].mean() if 'Temperature' in df else 0
            avg_pressure = df['Pressure'].mean() if 'Pressure' in df else 0
            avg_flowrate = df['Flowrate'].mean() if 'Flowrate' in df else 0

            buffer = io.BytesIO()

            p = canvas.Canvas(buffer, pagesize=letter)
            
            p.setFont("Helvetica-Bold", 16)
            p.drawString(100, 750, f"Analysis Report: {file_obj.file.name}")
            
            p.setFont("Helvetica", 12)
            p.drawString(100, 700, f"Total Equipment Count: {total_count}")
            
            p.drawString(100, 670, "Average Metrics:")
            p.drawString(120, 650, f"- Temperature: {avg_temp:.2f}")
            p.drawString(120, 630, f"- Pressure: {avg_pressure:.2f}")
            p.drawString(120, 610, f"- Flowrate: {avg_flowrate:.2f}")

            p.drawString(100, 580, "This report was generated by the Chemical Visualizer App.")
            
            p.showPage()
            p.save()

            buffer.seek(0)
            response = HttpResponse(buffer, content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="report_{pk}.pdf"'
            return response

        except UploadedFile.DoesNotExist:
            return Response({"error": "File not found"}, status=status.HTTP_404_NOT_FOUND)
        
class FileHistoryView(ListAPIView):
    queryset = UploadedFile.objects.all().order_by('-uploaded_at')[:5]
    serializer_class = FileUploadSerializer